### PR TITLE
Fixing interpretation of model

### PR DESCRIPTION
**Pull request by jdb78**
The current decomposition into a trend and seasonality does not work properly. This PR addresses the issue.

In essence, the problem is that the `dct` attribute of the model only stores predictions for one batch. This PR contributes a callback to save all predictions made

### CODE REVIEW

**Comment by takotab** [comment]
This is amazing!!! Thank you. 

Have you checked the index.ipynb? The CI seems fine so I guess it's not a problem but I've had problems there before. Could you check it?

**Comment by jdb78** [comment]
I indeed somehow did not export the interpret notebook. index.ipynb executes as expected - however its runs the old version as it clones the current repo from github. I guess one has to merge the PR and then re-create the docs. index.ipynb will then execute correctly

**Comment by takotab** [comment]
I tried to run the index.ipynb but got an error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-ba7135a05dc1> in <module>
----> 1 interp = NBeatsInterpretation.from_learner(learn)

~/dev/archive/fastseq/fastseq/nbeats/interpret.py in from_learner(cls, learn, ds_idx, dl, act)
     26         cb = Components()
     27         learn.add_cb(cb)
---> 28         res = learn.get_preds(dl=dl, with_input=True, with_loss=True, with_decoded=True, act=None, reorder=False)
     29         learn.remove_cb(cb)
     30         return cls(dl, *res, full_every_block=cb.stored)

~/dev/archive/fastseq/env/lib/python3.7/site-packages/fastai2/learner.py in get_preds(self, ds_idx, dl, with_input, with_decoded, with_loss, act, inner, **kwargs)
    210                   inner=False, **kwargs):
    211         if dl is None: dl = self.dls[ds_idx].new(shuffled=False, drop_last=False)
--> 212         cb = GatherPredsCallback(with_input=with_input, with_loss=with_loss, **kwargs)
    213         #with self.no_logging(), self.added_cbs(cb), self.loss_not_reduced(), self.no_mbar():
    214         ctx_mgrs = [self.no_logging(), self.added_cbs(cb), self.no_mbar()]

TypeError: __init__() got an unexpected keyword argument 'reorder'

```

**Comment by jdb78** [comment]
I think the difference might be here the version of `fastai2` from pip and from the github. I guess the newer version from github causes the error. Will confirm later today. We should probably drop the `reorder` keyword.

**Comment by jdb78** [comment]
I think your code might be outdated. When I look here, `get_preds()` does have a keyword `reorder`: https://github.com/fastai/fastai2/blob/master/fastai2/learner.py#L223

**Comment by takotab** [comment]
the reorder was there. It broke stuff so I fixed it last week (https://github.com/takotab/fastseq/pull/5) but now it seems they removed it again. very strange

**Pull request merged**
